// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc4843.FIRST2013;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController chassislmotor;
    public static SpeedController chassisrmotor;
    public static RobotDrive chassisrobotdrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        chassislmotor = new Victor(1, 1);
	LiveWindow.addActuator("chassis", "lmotor", (Victor) chassislmotor);
        
        chassisrmotor = new Victor(1, 2);
	LiveWindow.addActuator("chassis", "rmotor", (Victor) chassisrmotor);
        
        chassisrobotdrive = new RobotDrive(chassislmotor, chassisrmotor);
	
        chassisrobotdrive.setSafetyEnabled(true);
        chassisrobotdrive.setExpiration(0.1);
        chassisrobotdrive.setSensitivity(0.5);
        chassisrobotdrive.setMaxOutput(1.0);
        chassisrobotdrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
